# Generated by Django 5.0.4 on 2024-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_review_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review_connected",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="author",
            new_name="user",
        ),
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
            ),
        ),
    ]
