# Generated by Django 5.0.4 on 2024-04-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_rename_review_connected_review_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.book"
            ),
        ),
    ]
